-- MySQL Script generated by MySQL Workbench
-- Thu 04 Jul 2024 11:12:21 AM -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema medicMe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema medicMe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medicMe` DEFAULT CHARACTER SET utf8 ;
USE `medicMe` ;

-- -----------------------------------------------------
-- Table `medicMe`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicMe`.`usuarios` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `createDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medicMe`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicMe`.`medicos` (
  `medico_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthday` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `specialty_id` ENUM("Ortopedia", "Odontologia", "Optometria", "Pediatria", "Cardiologia", "Medicina General") NOT NULL COMMENT '\n	',
  `usuario_id` INT NOT NULL,
  `createDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `medicoscol` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`medico_id`),
  INDEX `fk_medicos_usuarios_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_medicos_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `medicMe`.`usuarios` (`usuario_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medicMe`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicMe`.`pacientes` (
  `paciente_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `birthdate` DATE NULL,
  `telephone` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `usuario_id` INT NULL,
  `pacientescol` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`paciente_id`),
  INDEX `fk_pacientes_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_pacientes_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `medicMe`.`usuarios` (`usuario_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medicMe`.`sedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicMe`.`sedes` (
  `sede_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sede_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medicMe`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicMe`.`reservas` (
  `reserva_id` INT NOT NULL,
  `paciente_id` INT NOT NULL,
  `medico_id` INT NOT NULL,
  `sede_id` INT NOT NULL,
  `appointment_id` INT NOT NULL,
  `createDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`reserva_id`),
  INDEX `fk_reservas_paciente_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `fk_reservas_medico_idx` (`medico_id` ASC) VISIBLE,
  INDEX `fk_reservas_sede_idx` (`sede_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_paciente`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `medicMe`.`pacientes` (`paciente_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservas_medico`
    FOREIGN KEY (`medico_id`)
    REFERENCES `medicMe`.`medicos` (`medico_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_sede`
    FOREIGN KEY (`sede_id`)
    REFERENCES `medicMe`.`sedes` (`sede_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
